### ISSUE TITLE
Boost\libs\random failed to build due to error C2039 on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [boostorg/random#82]
**Issue description:**
Boost\libs\random failed to build due to error C2039 on MSVC. Could you please take a look? We ues https://github.com/boostorg/boost/commit/ea9f9fbf1b0fef4c8a9eefc2dc0f24319f83cf8b from Boost master branch.

**Build step:**

1. git clone -c core.autocrlf=true --recursive ​https://github.com/boostorg/boost.git boost
2. open a VS 2019 x64 command prompt and browse to boost
3. .\bootstrap
4. .\b2 headers variant=release --build-dir=..\out\x64rel address-model=64
5. .\b2 variant=release --build-dir=..\out\x64rel address-model=64
6. .\b2 -j4 variant=release --build-dir=..\out\x64rel libs\random\test

**Error info:**
multiprecision_int_test.cpp
libs\random\test\multiprecision_int_test.cpp(37): error C2039: 'list': is not a member of 'boost::mpl'
.\boost/mpl/always.hpp(21): note: see declaration of 'boost::mpl'
libs\random\test\multiprecision_int_test.cpp(37): error C2143: syntax error: missing ';' before '<'
libs\random\test\multiprecision_int_test.cpp(37): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
libs\random\test\multiprecision_int_test.cpp(50): error C2065: 'engines': undeclared identifier
libs\random\test\multiprecision_int_test.cpp(50): error C2923: 'boost::unit_test::ut_detail::template_test_case_gen': 'engines' is not a valid template type argument for parameter 'TestTypesList'
libs\random\test\multiprecision_int_test.cpp(50): note: see declaration of 'engines'
libs\random\test\multiprecision_int_test.cpp(50): error C2976: 'boost::unit_test::ut_detail::template_test_case_gen': too few template arguments
.\boost/test/tree/test_case_template.hpp(155): note: see declaration of 'boost::unit_test::ut_detail::template_test_case_gen'
libs\random\test\multiprecision_int_test.cpp(50): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'boost::unit_test::ut_detail::template_test_case_gen'
libs\random\test\multiprecision_int_test.cpp(50): note: No constructor could take the source type, or constructor overload resolution was ambiguous
libs\random\test\multiprecision_int_test.cpp(50): error C2664: 'boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(int)': cannot convert argument 1 from 'boost::unit_test::decorator::collector_t' to 'int'

**Comment by jzmaddock** [comment]
Missing #includes, fixed by: https://github.com/boostorg/random/pull/83

**Comment by jwakely** [comment]
This was broken in 1.76.0 but seems to be fixed in 1.77.0, even though #83 never got merged.

I've included the unmerged pull request in the Fedora 1.76.0 package to fix a CI failure.

**Comment by QuellaZhang** [comment]
This issue still can be repro on [8bfc57e268c536f68d3832741bccdefad534d9d4](https://github.com/boostorg/boost/commit/8bfc57e268c536f68d3832741bccdefad534d9d4).

After apply patch, both of multiprecision_int_test.exe and multiprecision_float_test.exe are crash.

multiprecision_float_test.cpp
testing.capture-output ..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.run
====== BEGIN OUTPUT ======
 
EXIT STATUS: -1073740791 
====== END OUTPUT ======

    set Path=F:\gitP\boostorg\out\x86rel_1\boost\bin.v2\libs\test\build\msvc-14.2\release\threading-multi;%Path%

    set status=0
    if %status% NEQ 0 (
        echo Skipping test execution due to testing.execute=off
        exit 0
    )
     "..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.exe"   > "..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.output" 2>&1 
    set status=%ERRORLEVEL%
    echo. >> "..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.output"
    echo EXIT STATUS: %status% >> "..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.output"
    if %status% EQU 0 (
        copy "..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.output" "..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.run"
    )
    set verbose=0
    if %status% NEQ 0 (
        set verbose=1
    )
    if %verbose% EQU 1 (
        echo ====== BEGIN OUTPUT ======
        type "..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.output"
        echo ====== END OUTPUT ======
    )
    exit %status%

...failed testing.capture-output ..\out\x86rel_1\boost\bin.v2\libs\random\test\multiprecision_int_test.test\msvc-14.2\release\threading-multi\multiprecision_int_test.run...

**Comment by jzmaddock** [comment]
See also https://github.com/boostorg/random/pull/88
